In [113]:
import tensorflow
import numpy
from numpy.random import randint
from sklearn.model_selection import train_test_split

In [164]:
epochs = 30
sample_dim = 10
n_samples = 250
variaty = 20
test_size=0.15

In [165]:
X = randint(low=1, high=variaty, size=(n_samples, sample_dim))

In [166]:
y = numpy.sort(X)

In [167]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=test_size, random_state=42)

In [168]:
def preprocess(data):
    return data/variaty

In [169]:
X_train, y_train = preprocess(X_train), preprocess(y_train)

In [170]:
def create_model():
    model = tensorflow.keras.models.Sequential([
        tensorflow.keras.layers.InputLayer(
            input_shape=(sample_dim,)),
        tensorflow.keras.layers.Dense(256, activation='relu'),
        tensorflow.keras.layers.Dense(256, activation='relu'),
        tensorflow.keras.layers.Dropout(0.2),
        tensorflow.keras.layers.Dense(sample_dim, activation='sigmoid')
    ])

    model.compile(
        optimizer="adam",
        loss="mae",
        metrics=["accuracy"]
    )

    return model

In [171]:
model = create_model()
model.summary()

Model: "sequential_17"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_51 (Dense)             (None, 256)               2816      
_________________________________________________________________
dense_52 (Dense)             (None, 256)               65792     
_________________________________________________________________
dropout_17 (Dropout)         (None, 256)               0         
_________________________________________________________________
dense_53 (Dense)             (None, 10)                2570      
Total params: 71,178
Trainable params: 71,178
Non-trainable params: 0
_________________________________________________________________


In [172]:
history = model.fit(X_train, y_train, epochs=epochs, batch_size=32)

Epoch 1/30
7/7 [==============================] - 0s 9ms/step - loss: 0.2153 - accuracy: 0.0425
Epoch 2/30
7/7 [==============================] - 0s 10ms/step - loss: 0.1470 - accuracy: 0.0943
Epoch 3/30
7/7 [==============================] - 0s 11ms/step - loss: 0.1115 - accuracy: 0.2217
Epoch 4/30
7/7 [==============================] - 0s 8ms/step - loss: 0.1016 - accuracy: 0.7547
Epoch 5/30
7/7 [==============================] - 0s 10ms/step - loss: 0.0989 - accuracy: 0.8160
Epoch 6/30
7/7 [==============================] - 0s 10ms/step - loss: 0.0982 - accuracy: 0.8160
Epoch 7/30
7/7 [==============================] - 0s 9ms/step - loss: 0.0946 - accuracy: 0.8160
Epoch 8/30
7/7 [==============================] - 0s 10ms/step - loss: 0.0936 - accuracy: 0.8208
Epoch 9/30
7/7 [==============================] - 0s 12ms/step - loss: 0.0913 - accuracy: 0.8113
Epoch 10/30
7/7 [==============================] - 0s 10ms/step - loss: 0.0901 - accuracy: 0.8208
Epoch 11/30
7/7 [===============

In [173]:
y_pred = model.predict(preprocess(X_test)) 
y_pred = numpy.round(y_pred * variaty, 0)

In [178]:
X_test[2]

array([ 7,  3,  6,  7, 10,  9,  4, 17,  6,  8])

In [174]:
y_pred[2]

array([ 2.,  3.,  4.,  5.,  7.,  9., 10., 12., 14., 17.], dtype=float32)

In [175]:
y_test[2]

array([ 3,  4,  6,  6,  7,  7,  8,  9, 10, 17])

In [176]:
def calc_acc(y_pred, y_test):
    acc = []
    for i in range(int(n_samples*test_size)):
        acc.append(0)
        for j in range(sample_dim):
            acc[i] += ((y_pred[i][j] - y_test[i][j]) ** 2) ** 0.5

    return sum([acc_sample/sample_dim for acc_sample in acc])/n_samples

In [177]:
calc_acc(y_pred, y_test)

0.16839999999999994